language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
branches:
  only:
  - master
  - develop
script:
  mvn verify
